### ISSUE TITLE
Urgent: Critical Security Vulnerability Report Alert

### ISSUE THREAD

**Issue by yasir2904** [TV1-EU/magewell-exporter#1]
Hello Team,

I am an information security researcher and I found a critical security vulnerability on your website. Which can impact your business and users. This is an urgent attention requiring matter. I recommend you look into it ASAP. 

I want to report this security vulnerability professionally and responsibly.Do you offer a bug reward program for bug hunters?

Here is my profile glimpse for your reference 

https://hackerone.com/delta_094?type=user

[https://www.linkedin.com/in/yasir-iqbal-a11254162](https://hackerone.com/delta_094?type=user)

Waiting for your reply

Thanks

**Comment by adaichendt-tv1** [comment]
Hi Yasir! 

Sorry for my delayed response; I rarely check this account. Thank you for reaching out to us, we appreciate it. 

Could you please contact our privacy officer via mail at s.schlichtmeier@tv1.eu and disclose what website poses a security risk as we operate numerous sites?  

Thank you for your assistance! 

Best,
Alex

**Comment by yasir2904** [comment]
Hi,

I have already submitted report to your security team and this person still
I have no response from your side.

Kindly update me ASAP

Thanks

**Comment by yasir2904** [comment]
Hi,

Kindly contact your team and update me ASAP.

Thanks

**Comment by adaichendt-tv1** [comment]
I believe these things take their time as multiple departments are involved and it is holiday season. It is on their radar and your inquiry is being handled. 

Best, 
Alex

**Comment by yasir2904** [comment]
Hi,

I have submitted my vulnerability report on 20 may 2024 but still no update
from your side,
I have submitted my vulnerability and the issue is patched and now I'm
waiting for a hopeful update from your side.
Kindly contact your team about this and inform me.

Waiting for your response

Thanks

**Comment by adaichendt-tv1** [comment]
I already provided you the update. It is being handled. I am just a software engineer in a different department without insight into this process. Please inquire with responsible people. 

Best, 
Alex

**Comment by yasir2904** [comment]
Hi,

I understand your point, I have no response from your security department
after my submission. If you connect me with the right person it is grateful
for me.

Thanks
